samples/python/log-scanner-master/app/logscanner/models.py
from app import db


class Entry(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    timestamp = db.Column(db.DateTime)
    sip = db.Column(db.String(16))
    method = db.Column(db.String(10))
    uri = db.Column(db.Text)
    query = db.Column(db.Text)
    sport = db.Column(db.Integer)
    username = db.Column(db.String(256))
    cip = db.Column(db.String(16))
    useragent = db.Column(db.Text)
    referer = db.Column(db.Text)
    status = db.Column(db.Text)
    substatus = db.Column(db.Text)
    win32status = db.Column(db.Text)
    timetaken = db.Column(db.Text)
    country = db.Column(db.String(128))

    def __repr__(self):
        return '<Entry: {}>'.format(self.cip)


class Attack(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    entry_id = db.Column(db.Integer, db.ForeignKey('entry.id'))
    entry = db.relationship('Entry', backref=db.backref('attacks', lazy=True))
    ip = db.Column(db.String(16))
    type = db.Column(db.String(10))
    country = db.Column(db.String(128))

    def __repr__(self):
        return '<Attack: {} - {}>'.format(self.ip, self.type)

samples/python/log-scanner-master/app/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask_uploads import UploadSet, configure_uploads


log_upload = UploadSet('logs')

db = SQLAlchemy()
migrate = Migrate()


def create_app(config=None):
    app = Flask('log-scanner')

    app.config.from_object(config)

    # for uploading log file
    configure_uploads(app, log_upload)

    # database
    db.init_app(app)
    migrate.init_app(app, db)

    from app.logscanner.views import logscanner_page
    app.register_blueprint(logscanner_page)

    return app

samples/python/log-scanner-master/app/logscanner/views.py
import flask_uploads
import os
from flask import Blueprint, render_template, request, flash, redirect, url_for
from sqlalchemy import func

from app.logscanner.scanner import scan_log
from app import log_upload, db
from .models import Entry, Attack

logscanner_page = Blueprint('log_scanner_page', __name__,
                            template_folder='templates')


@logscanner_page.route('/', endpoint='index')
def index():
    return render_template('index.html')


@logscanner_page.route('/uniq_ip', endpoint='uniq_ip')
def uniq_ip():
    entries = db.session.query(Entry.cip).distinct(Entry.cip).all()
    return render_template('list_ip.html', entries=entries)

@logscanner_page.route('/uniq_ip_country', endpoint='uniq_ip_country')
def uniq_ip_country():
    entries = db.session.query(Entry.cip, Entry.country,
                               func.count(Entry.cip))\
        .group_by(Entry.cip, Entry.country).all()
    return render_template('list_ip_country.html', entries=entries)


@logscanner_page.route('/ip_activity/<string:ip>', endpoint='ip_activity')
def ip_activity(ip):
    entries = db.session.query(Entry).filter_by(cip=ip).order_by(Entry.timestamp).all()
    return render_template('list_ip_activity.html', ip=ip, entries=entries)


@logscanner_page.route('/attacks', endpoint='attacks')
@logscanner_page.route('/attacks/<string:type>', endpoint='attacks')
def attacks(type=None):
    entries = db.session.query(Attack)
    if type is not None:
        entries = entries.filter_by(type=type).all()
    return render_template('list_attacks.html', type=type, entries=entries)


@logscanner_page.route('/upload', methods=['GET', 'POST'], endpoint='upload')
def upload():
    if request.method == 'POST':
        log_file = request.files.get('log_file', None)
        if log_file is None:
            flash('Log file not found!', 'error')
            return redirect(request.url)

        try:
            filename = log_upload.save(log_file)

            # send the file to be scanned
            scan_log(os.path.join(log_upload.config.destination, filename))

            flash('Log uploaded and scanned...', 'success')
        except flask_uploads.UploadNotAllowed:
            flash('File not allowed for upload', 'error')
        return redirect(url_for('.index'))
    return render_template('index.html')

samples/python/log-scanner-master/app/logscanner/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Log Scanner</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <style>
        .starter-template {
            padding: 3rem 1.5rem;
            text-align: center;
        }
    </style>
    {% block style %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('.index') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('.uniq_ip') }}">Unique IP List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('.uniq_ip_country') }}">Unique IP - Country List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('.attacks') }}">Attacks List</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">
        <div class="starter-template">
    {% block body %}{% endblock %}
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
</body>
</html>

samples/python/log-scanner-master/app/logscanner/templates/index.html
{% extends "base.html" %}
{% block body %}
    <h1>Log Scanner</h1>
    <form method="post" action="{{ url_for('log_scanner_page.upload') }}" enctype="multipart/form-data">
        <div class="form-group">
            <label>Upload Log File (*.zip/*.log):</label>
            <label class="custom-file">
                <input class="custom-file-input" type="file" name="log_file">
                <span class="custom-file-control"></span>
            </label>
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }}">{{ message }}</div>
        {% endfor %}
      {% endif %}
    {% endwith %}
{% endblock %}

samples/python/log-scanner-master/app/logscanner/templates/list_attacks.html
{% extends "base.html" %}
{% block body %}
    {% if type is none %}
        <h1>Attacks</h1>
        {% else %}
        <h1>{{ type }} Attacks</h1>
    {% endif %}
    <table class="table table-striped">
        <tr>
            <th>Timestamp</th>
            <th>IP Address</th>
            <th>Country</th>
            <th>URI</th>
            <th>Query</th>
            <th>Possible attacks</th>
        </tr>
        {% for entry in entries %}
        <tr>
            <td>{{ entry.entry.timestamp }}</td>
            <td><a href="{{ url_for('.ip_activity', ip=entry.ip) }}">{{ entry.ip }}</a></td>
            <td>{{ entry.country }}</td>
            <td>{{ entry.entry.uri }}</td>
            <td>{{ entry.entry.query }}</td>
            <td>{{ entry.type }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

samples/python/log-scanner-master/app/logscanner/templates/list_ip.html
{% extends "base.html" %}
{% block body %}
    <h1>IP List</h1>
    <table class="table table-striped">
        <tr>
            <th>Client IP</th>
        </tr>
        {% for entry in entries %}
        <tr>
            <td><a href="{{ url_for('.ip_activity', ip=entry.0) }}">{{ entry.0 }}</a></td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

samples/python/log-scanner-master/app/logscanner/templates/list_ip_activity.html
{% extends "base.html" %}
{% block style %}
    {{ super() }}
    <style>
    .suspected {background-color: darkorange!important;}
    </style>
{% endblock %}
{% block body %}
    <h1>{{ ip }} activities</h1>
    <table class="table table-striped">
        <tr>
            <th>Timestamp</th>
            <th>URI</th>
            <th>Query</th>
            <th>Possible attacks</th>
        </tr>
        {% for entry in entries %}
            {% set suspect = False %}
            {% if entry.attacks|length > 0 %}
                {% set suspect = True %}
            {% endif %}
        <tr class="{{ 'suspected' if suspect else '' }}">
            <td>{{ entry.timestamp }}</td>
            <td>{{ entry.uri }}</td>
            <td>{{ entry.query }}</td>
            <td>{{ entry.attacks|join(', ', 'type') }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

samples/python/log-scanner-master/app/logscanner/templates/list_ip_country.html
{% extends "base.html" %}
{% block body %}
    <h1>IP - Country List</h1>
    <table class="table table-striped">
        <tr>
            <th>Client IP</th>
            <th>Country</th>
            <th>Hits</th>
        </tr>
        {% for entry in entries %}
        <tr>
            <td><a href="{{ url_for('.ip_activity', ip=entry.0) }}">{{ entry.0}}</a></td>
            <td>{{ entry.1 }}</td>
            <td>{{ entry.2 }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}